var rule = {
  类型: '影视',
  title: '小幺妹［密］',
  host: 'https://agqxyaomeisp.buzz',
  url: '/video/type/fyclass/fypage.html',
  searchUrl: '/video/lookup/**/L/fypage.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 1,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  timeout: 5000,
  class_parse: '.row .col-3:lt(42);a&&title;a&&href;.*/(.*?).html', 
  cate_exclude:'视频三区|视频二区|视频四区|特色专区',
  play_parse: true,
  lazy: "js:input = {parse: 1, url: input, js: ''}",
  double: true,
  推荐: '.row .col-sm-6;.col-sm-6;h2&&Text;img&&src;.position-absolute&&Text;a&&href',
  一级: '.col-sm-6;h2&&Text;img&&src;.text-dark&&Text;a&&href;.small&&Text',
  二级: {
    title: 'h1&&Text',
    img: 'img&&src',
    tabs: '',
    lists: '.table-striped:eq(#id)&&a',
  },
  搜索: '*',
}
